### ISSUE TITLE
Cannot Compile with Maven {Warning I'm new to maven.}

### ISSUE THREAD

**Issue by VinexAx789** [TheLightMC/Minigames#5]
`
C:\Users\Ryan\Desktop\Coding\Minigames-master>mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Minigames
[INFO] core
[INFO] spleef
[INFO] lms
[INFO] oitc
[INFO] tdm
[INFO] survivalgames
[INFO] skywars
[INFO] splegg
[INFO] runner
[INFO] uhc
[INFO] plugin
[INFO] sad
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Minigames 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Minigames ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building core 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.thelightmc.menu:MenuAPI:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Minigames .......................................... SUCCESS [  0.363 s]
[INFO] core ............................................... FAILURE [  0.725 s]
[INFO] spleef ............................................. SKIPPED
[INFO] lms ................................................ SKIPPED
[INFO] oitc ............................................... SKIPPED
[INFO] tdm ................................................ SKIPPED
[INFO] survivalgames ...................................... SKIPPED
[INFO] skywars ............................................ SKIPPED
[INFO] splegg ............................................. SKIPPED
[INFO] runner ............................................. SKIPPED
[INFO] uhc ................................................ SKIPPED
[INFO] plugin ............................................. SKIPPED
[INFO] sad ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.392 s
[INFO] Finished at: 2016-06-25T02:11:35-04:00
[INFO] Final Memory: 7M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project net.thelightmc.minigames:core:jar:1.0-SNAPSHOT: Failure to find net.thelightmc.menu:MenuAPI:jar:1.0-SNAPSHOT in http://ci.lilypadmc.org/plugin/repository/everything was cached in the local repository, resolution will not be reattempted until the update interval of lilypad has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

C:\Users\Ryan\Desktop\Coding\Minigames-master>`

**Comment by TheLightMC** [comment]
That's due to my menu api being missing. That's completely my fault as I had forgotten to upload it and I'll fix that soon.

**Comment by TheLightMC** [comment]
Alright I just pushed a new version that should be compatible, if it doesn't work just let me know and I'll make sure everything is correct.

**Comment by VinexAx789** [comment]
Eh thanks.

**Comment by VinexAx789** [comment]
Uh actually still not working

`Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Ryan>cd C:\Users\Ryan\Desktop\Coding\Minigames-master

C:\Users\Ryan\Desktop\Coding\Minigames-master>mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module C:\Users\Ryan\Desktop\Coding\Minigames-master\miners of C:\Users\Ryan\Desktop\Coding\Minigames-master\pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project net.thelightmc.minigames:Minigames:1.0-SNAPSHOT (C:\Users\Ryan\Desktop\Coding\Minigames-master\pom.xml) has 1 error
[ERROR]     Child module C:\Users\Ryan\Desktop\Coding\Minigames-master\miners of C:\Users\Ryan\Desktop\Coding\Minigames-master\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

C:\Users\Ryan\Desktop\Coding\Minigames-master>cd C:\Users\Ryan\Desktop\Coding\Minigames-master

C:\Users\Ryan\Desktop\Coding\Minigames-master>mvn
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module C:\Users\Ryan\Desktop\Coding\Minigames-master\miners of C:\Users\Ryan\Desktop\Coding\Minigames-master\pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project net.thelightmc.minigames:Minigames:1.0-SNAPSHOT (C:\Users\Ryan\Desktop\Coding\Minigames-master\pom.xml) has 1 error
[ERROR]     Child module C:\Users\Ryan\Desktop\Coding\Minigames-master\miners of C:\Users\Ryan\Desktop\Coding\Minigames-master\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

C:\Users\Ryan\Desktop\Coding\Minigames-master>`

**Comment by TheLightMC** [comment]
Ah I forgot to remove a beta gamemode from the pom, sorry for the inconvenience.

**Comment by VinexAx789** [comment]
No worries!

**Comment by YoloxPanda** [comment]
gg

**Comment by VinexAx789** [comment]
Sorry for being pain just trying to fix it all another error:

`n-reporting/2.2.1/maven-reporting-2.2.1.pom (2 KB at 26.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom (2 KB at 33.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom (15 KB at 197.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom (2 KB at 27.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-container-default/1.0-alpha-30/plexus-container-default-1.0-alpha-30.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-container-default/1.0-alpha-30/plexus-container-default-1.0-alpha-30.pom (4 KB at 61.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-containers/1.0-alpha-30/plexus-containers-1.0-alpha-30.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-containers/1.0-alpha-30/plexus-containers-1.0-alpha-30.pom (2 KB at 33.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/1.2-alpha-9/plexus-classworlds-1.2-alpha-9.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/1.2-alpha-9/plexus-classworlds-1.2-alpha-9.pom (4 KB at 54.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/1.0.10/plexus-1.0.10.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/1.0.10/plexus-1.0.10.pom (9 KB at 138.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom
Downloaded: https://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom (8 KB at 141.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom (25 KB at 408.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.7/maven-shared-utils-0.7.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.7/maven-shared-utils-0.7.pom (5 KB at 84.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-components/20/maven-shared-components-20.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-components/20/maven-shared-components-20.pom (5 KB at 92.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/24/maven-parent-24.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/24/maven-parent-24.pom (37 KB at 610.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/14/apache-14.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/14/apache-14.pom (15 KB at 256.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.pom (865 B at 14.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler/2.5/plexus-compiler-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler/2.5/plexus-compiler-2.5.pom (6 KB at 91.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.10/plexus-utils-3.0.10.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.10/plexus-utils-3.0.10.pom (4 KB at 52.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/3.3/plexus-3.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/3.3/plexus-3.3.pom (20 KB at 335.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.5/plexus-compiler-manager-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.5/plexus-compiler-manager-2.5.pom (690 B at 12.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.5/plexus-compiler-javac-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.5/plexus-compiler-javac-2.5.pom (769 B at 14.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compilers/2.5/plexus-compilers-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compilers/2.5/plexus-compilers-2.5.pom (2 KB at 23.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.jar (13 KB at 172.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar (50 KB at 336.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-parameter-documenter/2.2.1/maven-plugin-parameter-documenter-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.jar (48 KB at 222.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.jar (79 KB at 353.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.jar (174 KB at 729.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-parameter-documenter/2.2.1/maven-plugin-parameter-documenter-2.2.1.jar (22 KB at 88.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar (9 KB at 30.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar (223 KB at 770.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar (22 KB at 73.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar (17 KB at 52.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.jar (35 KB at 102.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.jar (86 KB at 235.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-descriptor/2.2.1/maven-plugin-descriptor-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.jar (26 KB at 66.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.jar (13 KB at 33.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.jar (30 KB at 66.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-monitor/2.2.1/maven-monitor-2.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-descriptor/2.2.1/maven-plugin-descriptor-2.2.1.jar (39 KB at 86.2 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.jar (153 KB at 343.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.jar (66 KB at 130.9 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-monitor/2.2.1/maven-monitor-2.2.1.jar (11 KB at 20.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-toolchain/2.2.1/maven-toolchain-2.2.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.7/maven-shared-utils-0.7.jar
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar (14 KB at 25.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar (28 KB at 51.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.5/plexus-compiler-manager-2.5.jar
Downloaded: https://repo.maven.apache.org/maven2/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar (324 KB at 578.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.5/plexus-compiler-javac-2.5.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-toolchain/2.2.1/maven-toolchain-2.2.1.jar (37 KB at 61.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar (25 KB at 41.3 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.5/plexus-compiler-manager-2.5.jar (5 KB at 7.4 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.5/plexus-compiler-javac-2.5.jar (19 KB at 29.8 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.7/maven-shared-utils-0.7.jar (167 KB at 260.8 KB/sec)
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 83 source files to C:\Users\Ryan\Desktop\Coding\Minigames-master\core\target\classes
[INFO] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/game/Game.java: C:\Users\Ryan\Desktop\Coding\Minigames-master\core\src\main\java\net\thelightmc\minigames\game\Game.java uses or overrides a deprecated API.
[INFO] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/game/Game.java: Recompile with -Xlint:deprecation for details.
[INFO] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/utils/RespawnUtil.java: C:\Users\Ryan\Desktop\Coding\Minigames-master\core\src\main\java\net\thelightmc\minigames\utils\RespawnUtil.java uses unchecked or unsafe operations.
[INFO] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/utils/RespawnUtil.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/team/GameTeam.java:[106,13] cannot find symbol
  symbol:   method addEntry(java.lang.String)
  location: variable team of type org.bukkit.scoreboard.Team
[ERROR] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/team/GameTeam.java:[121,13] cannot find symbol
  symbol:   method removeEntry(java.lang.String)
  location: variable team of type org.bukkit.scoreboard.Team
[ERROR] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/listeners/SpectateListener.java:[45,61] constructor MenuItem in class net.thelightmc.minigames.menu.MenuItem cannot be applied to given types;
  required: org.bukkit.inventory.ItemStack,int
  found: (inventory[...])); },org.bukkit.inventory.ItemStack,int
  reason: actual and formal argument lists differ in length
[ERROR] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/commands/sub/CmdSelect.java:[30,26] constructor MenuItem in class net.thelightmc.minigames.menu.MenuItem cannot be applied to given types;
  required: org.bukkit.inventory.ItemStack,int
  found: (inventory[...])); },org.bukkit.inventory.ItemStack,int
  reason: actual and formal argument lists differ in length
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Minigames .......................................... SUCCESS [  0.403 s]
[INFO] core ............................................... FAILURE [ 14.229 s]
[INFO] spleef ............................................. SKIPPED
[INFO] lms ................................................ SKIPPED
[INFO] oitc ............................................... SKIPPED
[INFO] tdm ................................................ SKIPPED
[INFO] survivalgames ...................................... SKIPPED
[INFO] skywars ............................................ SKIPPED
[INFO] splegg ............................................. SKIPPED
[INFO] runner ............................................. SKIPPED
[INFO] uhc ................................................ SKIPPED
[INFO] plugin ............................................. SKIPPED
[INFO] sad ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.791 s
[INFO] Finished at: 2016-06-26T13:08:28-04:00
[INFO] Final Memory: 23M/271M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project core: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/team/GameTeam.java:[106,13] cannot find symbol
[ERROR] symbol:   method addEntry(java.lang.String)
[ERROR] location: variable team of type org.bukkit.scoreboard.Team
[ERROR] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/team/GameTeam.java:[121,13] cannot find symbol
[ERROR] symbol:   method removeEntry(java.lang.String)
[ERROR] location: variable team of type org.bukkit.scoreboard.Team
[ERROR] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/listeners/SpectateListener.java:[45,61] constructor MenuItem in class net.thelightmc.minigames.menu.MenuItem cannot be applied to given types;
[ERROR] required: org.bukkit.inventory.ItemStack,int
[ERROR] found: (inventory[...])); },org.bukkit.inventory.ItemStack,int
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /C:/Users/Ryan/Desktop/Coding/Minigames-master/core/src/main/java/net/thelightmc/minigames/commands/sub/CmdSelect.java:[30,26] constructor MenuItem in class net.thelightmc.minigames.menu.MenuItem cannot be applied to given types;
[ERROR] required: org.bukkit.inventory.ItemStack,int
[ERROR] found: (inventory[...])); },org.bukkit.inventory.ItemStack,int
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

C:\Users\Ryan\Desktop\Coding\Minigames-master>`

**Comment by TheLightMC** [comment]
Alright, just did a test build with the new dependencies and everything should be good to go. There was an issue with the scoreboard api and the conflicting dependencies so that should be fixed now.

**Comment by VinexAx789** [comment]
Alright.

**Comment by VinexAx789** [comment]
Ty worked now how do I use this?

**Comment by TheLightMC** [comment]
You just run the jar that was produced or you can use it as a dependency to build your own games.

**Comment by VinexAx789** [comment]
That's good shit the Minigames one right?

**Comment by TheLightMC** [comment]
You only need to depend on the core module if you want to create your own games however the Minigames one including the dependencies should be the one with the pre-built games.

**Comment by YoloxPanda** [comment]
gg

**Comment by VinexAx789** [comment]
Is all the games done?

**Comment by AlfieC** [comment]
is all the memes dank?
